networks:
  teranode-network:
    name: my-teranode-network

services:
  kafka-shared:
    extends:
      file: ../base/docker-services.yml
      service: kafka-shared

  kafka-console-shared:
    extends:
      file: ../base/docker-services.yml
      service: kafka-console-shared
