apiVersion: 1

datasources:
  - name: Prometheus-1
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-1:9090
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
    version: 1

  - name: Prometheus-2
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-2:9090
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "5s"
    version: 1

  - name: Prometheus-3
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-3:9090
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "5s"
    version: 1
