repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: deploy/k8s/ingresses
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: golangci-lint
        name: Run go linter
        entry: make lint
        language: system
        types: [ go ]
