version: '3.8'

# Define a common base configuration for ubsv nodes
x-ubsv-base:
  &ubsv-base
  image: taal/ubsv:latest
  depends_on:
    - postgres
  networks:
    - ubsv-network
  volumes:
    - ./data:/app/data
  expose:
    - 8081-8093

networks:
  ubsv-network:
    name: my-ubsv-network

services:
  ubsv-builder:
    image: taal/ubsv:latest
    build:
      context: .
      dockerfile: local.Dockerfile
    networks:
    - ubsv-network
    entrypoint: ["pwd"]


  tx-blaster-builder:
    image: taal/blaster:latest
    build:
      context: .
      dockerfile: local.txblaster.Dockerfile
    networks:
    - ubsv-network
    entrypoint: ["pwd"]
    
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - ubsv-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: really_strong_password_change_me
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Define node-specific configurations as extensions
  p2p-bootstrap-1:
    build:
      context: ./modules/p2pBootstrap
      dockerfile: local.Dockerfile
    environment:
      P2P_BOOTSTRAP_PORT: 9901
      SETTINGS_CONTEXT: "docker.ci.ubsv1"
    networks:
      - ubsv-network
    ports:
      - "19901:9901"

  p2p-bootstrap-2:
    build:
      context: ./modules/p2pBootstrap
      dockerfile: local.Dockerfile
    environment:
      P2P_BOOTSTRAP_PORT: 9901
      SETTINGS_CONTEXT: "docker.ci.ubsv2"
    networks:
      - ubsv-network
    ports:
      - "29901:9901"

  p2p-bootstrap-3:
    build:
      context: ./modules/p2pBootstrap
      dockerfile: local.Dockerfile
    environment:
      P2P_BOOTSTRAP_PORT: 9901
      SETTINGS_CONTEXT: "docker.ci.ubsv3"
    networks:
      - ubsv-network
    ports:
      - "39901:9901"

  ubsv-1:
    <<: *ubsv-base
    command: ["./ubsv", "-miner=1", "-coinbase=0"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv1"
      startCoinbase: false
      utxostore: postgres://miner1:miner1@postgres:5432/ubsv1
      txmeta_store: postgres://miner1:miner1@postgres:5432/ubsv1
      blockchain_store: postgres://miner1:miner1@postgres:5432/ubsv1
      coinbase_store: postgres://coinbase:coinbase@postgres:5432/coinbase
      startTxStore: "true"
      txstore: file:///data/ubsv1/txstore
      subtreestore: file:///data/ubsv1/subtreestore
      mine_initial_blocks: true
      mine_initial_blocks_count: 300
      miner_wallet_private_keys: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q | KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k | L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      coinbase_wallet_private_key: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q"
      startBootstrap: false
      startP2P: true
      feature_libP2P: true
      feature_bootstrap: false
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      blockchain_grpcAddress: "ubsv-1:8087"
      blockvalidation_httpAddress: "http://localhost:8088"
      coinbase_should_wait: true
      coinbase_wait_until_block: 200
      propagation_grpcAddresses: localhost:8084 | ubsv-2:8084 | ubsv-3:8084
      p2p_dht_use_private: true
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
    # volumes:
    #   - ./data/ubsv1/txstore:/data/ubsv1/txstore
    #   - ./data/ubsv1/subtreestore:/data/ubsv1/subtreestore
    ports:
      - "18081-18089:8081-8089"
      - "18090-18092:8090-8092"

  ubsv-1-coinbase:
    <<: *ubsv-base
    command: ["./ubsv", "-miner=0", "-coinbase=1"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv1"
      startBlockValidation: false
      startBlockAssembly: false
      utxostore: postgres://miner1:miner1@postgres:5432/ubsv1
      txmeta_store: postgres://miner1:miner1@postgres:5432/ubsv1
      blockchain_store: postgres://miner1:miner1@postgres:5432/ubsv1
      coinbase_store: postgres://coinbase1:coinbase1@postgres:5432/coinbase1
      startTxStore: "false"
      mine_initial_blocks_count: 200
      miner_wallet_private_keys: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q | KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k | L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      coinbase_wallet_private_key: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q"
      startBootstrap: false
      startP2P: false
      feature_libP2P: false
      feature_bootstrap: false
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      blockchain_grpcAddress: "ubsv-1:8087"
      coinbase_should_wait: true
      coinbase_wait_until_block: 200
      coinbase_grpcAddress: localhost:8093
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
    # volumes:
    #   - ./data/ubsv1/txstore:/data/ubsv1/txstore
    #   - ./data/ubsv1/subtreestore:/data/ubsv1/subtreestore
    ports:
      - "18093-19099:8093-9099"
    expose:
      - 8093-9099

  ubsv-2:
    <<: *ubsv-base
    command: ["./ubsv", "-miner=0", "-coinbase=0"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv2"
      startCoinbase: false
      utxostore: postgres://miner2:miner2@postgres:5432/ubsv2
      txmeta_store: postgres://miner2:miner2@postgres:5432/ubsv2
      blockchain_store: postgres://miner2:miner2@postgres:5432/ubsv2
      coinbase_store: postgres://coinbase:coinbase@postgres:5432/coinbase
      startTxStore: "true"
      txstore: file:///data/ubsv2/txstore
      subtreestore: file:///data/ubsv2/subtreestore
      miner_wallet_private_keys: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q | KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k | L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      coinbase_wallet_private_key: "KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k"
      startBootstrap: false
      feature_bootstrap: false
      startP2P: true
      feature_libP2P: true
      mine_initial_blocks: false
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      blockchain_grpcAddress: "ubsv-2:8087"
      blockvalidation_httpAddress: "http://localhost:8088"
      coinbase_should_wait: true
      coinbase_wait_until_block: 200
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      # p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
    volumes:
      - ./data/ubsv2/txstore:/data/ubsv2/txstore
      - ./data/ubsv2/subtreestore:/data/ubsv2/subtreestore
    ports:
      - "28081-28089:8081-8089"
      - "28090-28092:8090-8092"

  ubsv-2-coinbase:
    <<: *ubsv-base
    command: ["./ubsv", "-miner=1", "-coinbase=1"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv2"
      startBlockValidation: false
      startBlockAssembly: false
      utxostore: postgres://miner2:miner2@postgres:5432/ubsv2
      txmeta_store: postgres://miner2:miner2@postgres:5432/ubsv2
      blockchain_store: postgres://miner2:miner2@postgres:5432/ubsv2
      coinbase_store: postgres://coinbase2:coinbase2@postgres:5432/coinbase2
      startTxStore: "false"
      # txstore: badger:///data/ubsv2/txstore
      # subtreestore: badger:///data/ubsv2/subtreestore
      miner_wallet_private_keys: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q | KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k | L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      coinbase_wallet_private_key: "KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k"
      startBootstrap: false
      startP2P: false
      feature_libP2P: false
      feature_bootstrap: false
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      blockchain_grpcAddress: "ubsv-2:8087"
      coinbase_should_wait: true
      coinbase_wait_until_block: 200
      coinbase_grpcAddress: localhost:8093
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      # p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
    volumes:
      - ./data/ubsv1/txstore:/data/ubsv1/txstore
      - ./data/ubsv1/subtreestore:/data/ubsv1/subtreestore
    ports:
      - "28093-28093:8093-8093"

  tx-blaster-1:
    container_name: tx-blaster-1
    image: taal/blaster:latest
    depends_on:
      - postgres
      - ubsv-1
      - ubsv-2
    environment:
      SETTINGS_CONTEXT: "docker.ci"
      tx_blaster_profilerAddr: ":9092"
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      coinbase_grpcAddress: ubsv-1-coinbase:8093
      coinbase_store: postgres://coinbase1:coinbase1@postgres:5432/coinbase1
      blockchain_store: postgres://miner1:miner1@postgres:5432/ubsv1
      utxostore: postgres://miner1:miner1@postgres:5432/ubsv1
      coinbase_assetGrpcAddress: ubsv-1:8091
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      p2p_dht_use_private: true
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      # p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      # p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
      propagation_quicAddresses: https://ubsv-1:8384 | https://ubsv-2:8384 | https://ubsv-3:8384
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
    # pass arguments to the command
    command: ["./blaster.run", "-workers=1", "-print=0", "-profile=:9092", "-log=0", "-limit=200", "--quic=true"]
    networks:
      - ubsv-network
    volumes:
      - ./data/txblaster1:/app/data
      # - ./data/txblaster.log:/app/data/txblaster.log

  tx-blaster-2:
    container_name: tx-blaster-2
    image: taal/blaster:latest
    depends_on:
      - postgres
      - ubsv-1
      - ubsv-2
    environment:
      SETTINGS_CONTEXT: "docker.ci"
      tx_blaster_profilerAddr: ":9092"
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      coinbase_grpcAddress: ubsv-2-coinbase:8093
      coinbase_store: postgres://coinbase2:coinbase2@postgres:5432/coinbase2
      blockchain_store: postgres://miner2:miner2@postgres:5432/ubsv2
      utxostore: postgres://miner2:miner2@postgres:5432/ubsv2
      coinbase_assetGrpcAddress: ubsv-2:8091
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      BLASTER_ARGS: "-workers=2"
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
      # p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      propagation_quicAddresses: https://ubsv-1:8384 | https://ubsv-2:8384 | https://ubsv-3:8384
    # pass arguments to the command
    command: ["./blaster.run", "-workers=1", "-print=0", "-profile=:9092", "-log=0", "-limit=200", "--quic=true"]
    networks:
      - ubsv-network
    volumes:
      - ./data/txblaster2:/app/data
      # - ./data/txblaster.log:/app/data/txblaster.log

  ubsv-3:
    <<: *ubsv-base
    command: ["./ubsv", "-miner=0", "-coinbase=0"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv3"
      startCoinbase: false
      utxostore: postgres://miner3:miner3@postgres:5432/ubsv3
      txmeta_store: postgres://miner3:miner3@postgres:5432/ubsv3
      blockchain_store: postgres://miner3:miner3@postgres:5432/ubsv3
      coinbase_store: postgres://coinbase3:coinbase3@postgres:5432/coinbase
      startTxMetaStore: "true"
      startTxStore: "true"
      txstore: file:///data/ubsv3/txstore
      subtreestore: file:///data/ubsv3/subtreestore
      miner_wallet_private_keys: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q | KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k | L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      coinbase_wallet_private_key: "L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      startBootstrap: false
      feature_bootstrap: false
      startP2P: true
      feature_libP2P: true
      mine_initial_blocks: false
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      blockchain_grpcAddress: "ubsv-3:8087"
      blockvalidation_httpAddress: "http://localhost:8088"
      coinbase_should_wait: true
      coinbase_wait_until_block: 200
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
    volumes:
      - ./data/ubsv3/txstore:/data/ubsv3/txstore
      - ./data/ubsv3/subtreestore:/data/ubsv3/subtreestore
    ports:
      - "38081-38089:8081-8089"
      - "38090-38092:8090-8092"

  ubsv-3-coinbase:
    <<: *ubsv-base
    command: ["./ubsv", "-miner=1", "-coinbase=1"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv3"
      startBlockValidation: false
      startBlockAssembly: false
      utxostore: postgres://miner3:miner3@postgres:5432/ubsv3
      txmeta_store: postgres://miner3:miner3@postgres:5432/ubsv3
      blockchain_store: postgres://miner3:miner3@postgres:5432/ubsv3
      coinbase_store: postgres://coinbase3:coinbase3@postgres:5432/coinbase3
      startTxMetaStore: "false"
      startTxStore: "false"
      miner_wallet_private_keys: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q | KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k | L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      coinbase_wallet_private_key: "L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      startBootstrap: false
      startP2P: false
      feature_libP2P: false
      feature_bootstrap: false
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      blockchain_grpcAddress: "ubsv-3:8087"
      coinbase_should_wait: true
      coinbase_wait_until_block: 200
      coinbase_grpcAddress: localhost:8093
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
    volumes:
      - ./data/ubsv3/txstore:/data/ubsv3/txstore
      - ./data/ubsv3/subtreestore:/data/ubsv3/subtreestore
    ports:
      - "38093-38093:8093-8093"

  tx-blaster-3:
    container_name: tx-blaster-3
    image: taal/blaster:latest
    depends_on:
      - postgres
      - ubsv-1
      - ubsv-2
    environment:
      SETTINGS_CONTEXT: "docker.ci"
      tx_blaster_profilerAddr: ":9092"
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      coinbase_grpcAddress: ubsv-3-coinbase:8093
      coinbase_store: postgres://coinbase3:coinbase3@postgres:5432/coinbase3
      blockchain_store: postgres://miner3:miner3@postgres:5432/ubsv3
      utxostore: postgres://miner3:miner3@postgres:5432/ubsv3
      coinbase_assetGrpcAddress: ubsv-3:8091
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      BLASTER_ARGS: "-workers=2"
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK|/dns4/p2p-bootstrap-2/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
      propagation_quicAddresses: https://ubsv-1:8384 | https://ubsv-2:8384 | https://ubsv-3:8384
    # pass arguments to the command
    command: ["./blaster.run", "-workers=1", "-print=0", "-profile=:9092", "-log=0", "-limit=200", "--quic=true"]
    networks:
      - ubsv-network
    volumes:
      - ./data/txblaster2:/app/data
      # - ./data/txblaster.log:/app/data/txblaster.log


# Add more ubsv nodes as needed
