global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  # - job_name: "prometheus"
  #   static_configs:
  #     - targets: ["localhost:9090"]

  - job_name: "ubsv-3"
    static_configs:
      - targets: ["ubsv-3:9091"]
  - job_name: "aerospike-exporter-3"
    static_configs:
      - targets: ["aerospike-exporter-3:9145"]
