name: Build run container image
on: workflow_dispatch

env:
  REPO: teranode
  ECR_REGION: eu-north-1

jobs:
  build-run:
    name: Build run container image
    runs-on: ubuntu-latest
    strategy: # This will cause the workflow to terminate if any job fails
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # with:
        #   buildkitd-flags: --debug # Debug logs

      # Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REGION }}

      # Authenticate Docker to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      # Get a short unique identifier
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Set metadata for tags and labels
      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REPO }}
          tags: |
            type=raw,value=base-run-latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=base-run-${{ steps.vars.outputs.sha_short }}

      # Build Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./deploy/docker/Dockerfile_run_base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
