name: long-tests
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID from the triggering workflow'
        required: false
        type: string

env:
  REPO: teranode
  SETTINGS_CONTEXT_DEFAULT: test
  GO_VERSION: '1.25.2'

jobs:
  longtest:
    name: Long Tests (${{ github.event.inputs.run_id || 'scheduled' }})
    runs-on: teranode-runner-16-core
    steps:
      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@f974e0c5942f8f37973c4cc395704165fbe629ba # v2
        with:
          theme: "dark"
          comment_on_pr: "false"

      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ vars.DOCKER_ORG }}
          password: ${{ secrets.DOCKER_ORG_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Run Services Tests
        run: |
          make testall
        continue-on-error: false
